services:
  app:
    image: fortress-of-the-fallen:latest
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - fortress-of-the-fallen
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  fortress-of-the-fallen:
    external: true